quarkus.application.name=windsurf-service

%dev.windsurf.api-key=${WINDSURF_API_KEY:1111}
%test.windsurf.api-key=test-only
%prod.windsurf.api-key=${WINDSURF_API_KEY}

quarkus.rest-client.open-meteo.url=https://api.open-meteo.com
quarkus.rest-client.overpass.url=https://overpass-api.de
quarkus.rest-client.overpass.read-timeout=120000
quarkus.rest-client.overpass-discovery.url=https://overpass-api.de
quarkus.rest-client.overpass-discovery.connect-timeout=15000
quarkus.rest-client.overpass-discovery.read-timeout=30000

quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0

quarkus.swagger-ui.always-include=false

quarkus.http.auth.permission.permit-all.paths=/*
quarkus.http.auth.permission.permit-all.policy=permit

%dev.quarkus.mongodb.connection-string=${MONGODB_URL:mongodb://localhost:27017}
%prod.quarkus.mongodb.connection-string=${MONGODB_URL}
%test.quarkus.mongodb.devservices.enabled=true
quarkus.mongodb.database=${MONGODB_DATABASE:windsurf}
